%%{init: {
    "theme": "base",
        "themeVariables": {
        "primaryColor": "#FFFFFF",
        "primaryTextColor": "#6c6f85",
        "tertiaryTextColor": "#4c4f69",
        "lineColor": "#5c5f77"
        }
}}%%

flowchart TD
    A[**A Barrier In My Mind**: <br> Translating Lived Experience To Auxilium]
        A1[**My Brain Never Sleeps**: <br> Debilitating Daily Experiences]
        A2[**Work Is Grey**: <br> Necessity Of Convenience, Consistency And Customisation]
        A3[**A Reminder Of How Things Actually Are**: <br> Keeping An Emotional Inventory]
        
    B[**An All-In-One Companion**: <br> Future Forward Extensions Of Auxilium]
        B1[**That Makes Sense ... My Life Makes Sense**: <br> Power In Knowledge And Community]
        B2[**Give Me Something Easier**: <br> Digital Body Doubling Companion]
        B3[**Out Of Sight Out Of Mind**: <br> Simple Assistive Technology]

    style A stroke: #babbf1
        style A1 stroke: #ef9f76
        style A2 stroke: #ef9f76
        style A3 stroke: #ef9f76

    style B stroke: #babbf1
        style B1 stroke: #ef9f76
        style B2 stroke: #ef9f76
        style B3 stroke: #ef9f76


    A1 ~~~ A2 ~~~ A3 
    B1 ~~~ B2 ~~~ B3

    A --> A1
    A --> A2
    A --> A3
    B --> B1
    B --> B2
    B --> B3